### PR TITLE
Implement remaining texture wrapping modes

### PR DESCRIPTION
**Pull request by scurest**
This PR mostly implements the previously-unsupported wrapping modes: two 
disequal wrapping modes in the S- and T-directions, and MIRROED_REPEAT for any
direction. Blender doesn't support these through the "Extension" property on the
Image Texture node so they are implemented by inserting nodes to transform the
texcoords before feeding them into the texture node.

The complete set of nodes that can feed into the Image Texture node now like
this (you can see the nodes are now positioned nicely too)

nodes

The wrapping mode frame splits the texcoord into its components, applies group
nodes that do the wrapping formulas, and then combines them again. The wrapping
formulas are

formulas

Two new groups were added to node_groups.json to handle these. The group for
REPEAT looks like

repeat_group

When you compute x mod 1 with a Modulo node, you get an output with the same
sign as x, so the Add and Less Than nodes are there to get a result in the range
[0, 1).

The group for MIRRORED_REPEAT looks like

mirrored_repeat_group

The first frame computes x' = x mod 2 (with the same correction to get a number
in [0, 2)). The last frame lerps between x' and 2-x' using an interpolation that
is either 0 or 1 based on whether x' is less or greater than 1. AFAICT, there is
no pre-made node that does lerping for values (unlike RGBs and Shaders, which
have MixNodes). 

There is no group for clamping (which is too bad because it would be the
simplest one ^^). Clamping is handled by just passing the coordinate on through
because we set the "Extension" property on the Image Texture node to do clamping
directly.

(And obviously if both directions use clamp or repeat, we forgo creating the
Wrapping Mode frame and just set the "Extension" property correctly.)

If you view the sample TextureSettingTest in the Rendered view, the wrapping
mode tests are now all correct

test

There are two problems with this approach.

The first is accidental and Blender-specific: you do have to look in the
Rendered view because Blender appears to always use repeat for the "Extension"
of Image Textures in the Material view. So textures that should use clamping
look wrong in the Material view. This could be (partially, see below) mitigated
by using a "useless" group to do clamping even when the Image Texture is set to
do clamping itself.

The second is essential and conceptual: the wrapping mode should properly
interact with filtering, and just changing the texture coordinates does not.
This means that small errors are possible when the wrapped coordinate is very
near the border of the texture because the samples used for filtering that "lie
just outside the border" are determined by the real wrapping mode.

Here is an example using linear filtering. Suppose we have a 2x1 texture. There
are two samples, a and b, which lie at respectively (1/3, 1/2), and (2/3, 1/2)
in the [0,1]x[0,1] texture space. If we have a texcoord of t = (-1/2, 1/2), then
if the wrapping mode were _really_ CLAMP_TO_EDGE (in the S-direction), sampling
at t would give a. However, if the wrapping mode was _really_ REPEAT and we only
_emulated_ CLAMP_TO_EDGE by transforming t to t' = (0, 1/2), sampling there
would give (a+b)/2, _not_ a, because the samples that are selected for filtering
are determined by the real wrapping mode, which thinks t' is half-way between a
at (1/3, 1/2) and b repeated at (-1/3, 1/2).

So if we emulate CLAMP_TO_EDGE on a texture that is really REPEAT, points near
the edge might be influenced by samples waaay on the other side of the texture.
There is a similar error if we emulate MIRRORED_REPEAT.

For a real mode of CLAMP_TO_EDGE, there are also errors but they are not as bad,
which is why this is how I chose to implement things.

* Obviously emulating clamping if the real mode is CLAMP_TO_EDGE is perfect.
* Emulating MIRRORED_REPEAT is also perfect, since the samples that lie just
  outside the border are the same as those on the inside.
* The error is in REPEAT, when a point near the border should be influenced by a
  sample on the inside of the border and another near the border on the opposite
  side of the image, but it is only influenced by the first of these ie. we
  should have (a+b)/2 but we actually only have a, if we were to continue the
  example above. This is in some sense less bad than having a point be
  influenced by a sample it isn't supposed to be, because we can still think of
  this as a RPEAT texture, it just basiclly uses NEAREST filtering for points
  very close to the borders. Additionally, REPEAT textures are usually periodic,
  so the first and last sample in a row (or column) are close together, so there
  usually isn't much difference between a and (a+b)/2.

Which is all mostly just to register the fact that this implementation method
for wrapping is not perfect.

One more thing: Blender can't set the filtering in the s- and t-directions
independantly. This PR also selects the "best" of the two filters in the glTF to
use (previously I had just arbitrarily used the first) where LINEAR is better
than NEAREST. This is similar to cinghiale's idea to use the strongest of the two
magnifications for a camera's magnification.

-----

The history looks weird for the same reason as #32.

### CODE REVIEW

**Comment by scurest** [comment]
About clipping not working in the Material view, see https://developer.blender.org/T53468.

**Comment by ksons** [comment]
@scurest I merged #31 and #32 now keeping the history (should not use the github interface which squashes history by default). While number #36 merges without conflict, this one has a conflict. I think, only line 564 moved for some strange reason and should be in line 310 instead. Can you check?

I would merge your other two PRs and release version 0.4. Then I'd hand over the repository to you as you run the show anyway. Okay with you?

**Comment by scurest** [comment]
@kson Thanks a lot! Yeah, this branch is a sibling to master now. Actually if you merge #36 you'll get the changes from this PR too and Github will probably mark this one as merged automatically. But if you want, how about this instead: I can close these two PRs and open a new PR for my current master. That has all the changes from these two plus some more like support for animating material properties and working CUBICSPLINE interpolation, and it won't have any conflicts so it should be an easy merge. You could do a 0.4 release after that. How's that sound?

If you don't want it anymore I can take it. I'm not sure how deployment or CI works though. If you want to keep it but just don't have time to review PRs you could make me a collaborator and I could push my own stuff and handle some of the issues for you. Honestly if you get my master branch merged the importer will be really close to being feature-complete so things will probably settle into maintenance mode soon. The biggest thing on the horizon is probably Blender's 2.8 release.

**Comment by ksons** [comment]
@scurest You should have received an invite as collaborator. Both solution would make sense for me, I just don't want to be the bottleneck nor earn the credits that belong to a larger part to you.

I think a new PR could make sense. Looking forward for the new functionality. Material animations sound great. Any good scenes to test those?

**Comment by scurest** [comment]
@ksons Cool, I got it, thanks! #40 is the new PR.

I don't know any examples in the wild. But you can now do things like animate the offset of a texture transform with a STEP animation to play a 2D animation on a quad. This file plays an explosion animation: https://www.filedropper.com/bomb_1 (hope that file host works). Put your 3D View in Rendered mode because Blender doesn't update the Material view when material animations play.

**Comment by ksons** [comment]
Sounds good. The Link to filedropper doesn't work for me.

**Pull request closed without merging**
